services:
  - type: worker
    name: mysql-db
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 10
